title = "Bash.ID - Watch and Learn"
baseURL = "https://bashidorg.github.io/"
tags = ["blog", "tutorial"]
languageCode = "en-US"
config = "config.toml"
theme = "bashid"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "$ rm -rf *"
    author = "bhrdn"
    description = "Group for discussing scripting for bash, sh, zsh or any other shell in the GNU/Linux"
    logoBig = "/images/bashid-logo.png"
    logoSmall = "/images/bashid-logo.png"
    favicon = "/images/favicon.ico"
    opengraphImage = "/images/osprey.png"
    github = ""
    email = ""
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = false
    customCSS = true
    cacheBustCSS = true
    cacheBustJS = false
    ajaxFormspree = false

[[menu.main]]
    name = "Articles"
    url  = "/#articles"
    weight = 1
[[menu.main]]
    name = "Kulgram"
    url  = "/#kulgram"
    weight = 2
[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 3
